server:
  port: 8080
  address: 0.0.0.0

spring:
  datasource:
    username: root
    password: 5523
    url: jdbc:mysql://localhost:3306/hadoop?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  hadoop:
    config:
      fs.defaultFS: hdfs://localhost:9000
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 4GB
  mvc:
    static-path-pattern: /static/**

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: org.jetbrains.hadoop_netdisk.entity


logging:
  level:
    org:
      jetbrains:
        hadoop_netdisk:
          mapper: debug
